## check development version of mboost
## see http://docs.travis-ci.com/user/languages/r/

language: r
warnings_are_errors: false

r_github_packages:
  - boost-R/mboost
  - boost-R/gamboostLSS
  - jimhester/covr

# installing packages in Enhances  
r_packages:
  - glmnet
  - lars
  - mboost
  - gamboostLSS
  - QUIC
  - rmarkdown
  
after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
